language: python

cache: apt

compiler:
  - gcc

os: linux

jobs:
  include:
    - python: "3.6"
      arch: amd64
      env: WHEEL_PLATFORM=linux_x86_64

    - python: "3.6"
      arch: arm64
      env: WHEEL_PLATFORM=linux_aarch64

    - python: "3.7"
      arch: amd64
      env: WHEEL_PLATFORM=linux_x86_64

    - python: "3.7"
      arch: arm64
      env: WHEEL_PLATFORM=linux_aarch64

    - python: "3.8"
      arch: amd64
      env: WHEEL_PLATFORM=linux_x86_64

    - python: "3.8"
      arch: arm64
      env: WHEEL_PLATFORM=linux_aarch64

    - python: "3.9"
      arch: amd64
      env: WHEEL_PLATFORM=linux_x86_64

    - python: "3.9"
      arch: arm64
      env: WHEEL_PLATFORM=linux_aarch64

addons:
  apt:
    packages:
      - libsystemd-dev
      - patchelf

script:
  - pip install cython auditwheel
  - pip wheel . -w temp
  - auditwheel repair --plat $WHEEL_PLATFORM temp/*.whl -w dist/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/*.whl
  file_glob: true
  skip_cleanup: true
  on:
    repo: mosquito/cysystemd
    tags: true
