on:
  push:
    tags:
      - '*.*.*'

name: Build binary packages

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test docker
        run: docker ps

#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Builder instance name
#        run: echo ${{ steps.buildx.outputs.name }}
#
#      - name: Available platforms
#        run: echo ${{ steps.buildx.outputs.platforms }}
#
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
#          draft: false
#          prerelease: false
