on:
  push:
    tags:
      - '*.*.*'

name: Build linux wheels

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Install python dependencies
        run: >
          sudo apt-get install -y
          python3-dev
          python3-pip
          python3-setuptools
          python3-distutils

      - name: Install build dependencies
        run: >
          sudo python3 -m pip install cython

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create sdist package
        run: python3 setup.py sdist

      - name: Build image
        run: docker build -t cysystemd:manylinux -f Dockerfile.manylinux .

      - name: Build wheels
        run: >
          docker run --rm
          -v $(pwd):/app/src:ro
          -v $(pwd)/dist:/app/dst
          --entrypoint /bin/bash
          cysystemd:manylinux
          /app/src/scripts/make-wheels.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
